config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'	# named routes
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	get '/index', to: 'users#index'
	get '/notification/:id/link_through', to: 'notifications#link_through',
										 as: :link_through
	get '/notifications', to: 'notifications#index'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :comments,		only: [:create, :destroy]
	resources :likes, 			only: [:create, :destroy]
	resources :users
	resources :microposts,		only: [:create, :destroy, :show]
	resources :relationships,	only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :user
	belongs_to :micropost
	belongs_to :notified_by, class_name: "User"
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	def link_through
		@notification = Notification.find_by(id: params[:id])
		@notification.update read: true
		redirect_to micropost_path(@notification.micropost)
	end

	def index
		@notifications = current_user.notifications
			.paginate(page: params[:page], per_page: 6).order("id DESC")
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% if notification.read == true %>
	<li class="notification">
		<%= link_to link_through_path(notification) do %>
			<% if notification.notified_by.avatar? %>
				<%= image_tag notification.notified_by.avatar.url(:thumb) %>
			<% else %>
				<% if notification.notified_by.gender == "Male" %>
					<%= image_tag notification.notified_by.avatar.default_url("ava-default-male.jpg") %>
				<% else %>
					<%= image_tag notification.notified_by.avatar.default_url("ava-default-female.png") %>
				<% end %>
			<% end %>
			<div class="notifi-content">
				<strong><%= notification.notified_by.name %></strong> has 
				<%= notification.notifi_type %>ed on your post
			</div>
			<div class="notifi-time">
				<%= time_ago_in_words(notification.created_at) %>
			</div>
		<% end %>
	</li>
<% else %>
	<li class="notification unread">
		<%= link_to link_through_path(notification) do %>
			<% if notification.notified_by.avatar? %>
				<%= image_tag notification.notified_by.avatar.url(:thumb) %>
			<% else %>
				<% if notification.notified_by.gender == "Male" %>
					<%= image_tag notification.notified_by.avatar.default_url("ava-default-male.jpg") %>
				<% else %>
					<%= image_tag notification.notified_by.avatar.default_url("ava-default-female.png") %>
				<% end %>
			<% end %>
			<div class="notifi-content">
				<strong><%= notification.notified_by.name %></strong> has 
				<%= notification.notifi_type %>ed on your post
			</div>
			<div class="notifi-time">
				<%= time_ago_in_words(notification.created_at) %>
			</div>
		<% end %>
	</li>
<% end %>

app/views/notifications/index.html.erb
<div class="main-content">
	<div class="notifications">
		<div class="heading">Notifications list</div>
		<ul>
			<%= render @notifications %>
		</ul>
		<%= will_paginate @notifications, class: "pagination-notifies" %>
	</div>
	<%= render 'static_pages/home_right_block' %>
</div>

<script type="text/javascript">
	$(function() {
		if ($('.pagination-notifies').length) {
			$(window).scroll(function() {
				var url = $('.pagination-notifies .next_page').find("a").attr('href');
				if (url && url != '#' && $(window).scrollTop() > $(document).height() - $(window).height() - 10) {
					$('.pagination-notifies').html(
						"<i class='fa fa-spinner fa-spin fa-3x fa-fw'></i>"
						+ "<span class='sr-only'>Loading...</span>");
					console.log(url);
					return $.getScript(url);
				}
			});
			return $(window).scroll();
		}
	});
</script>

app/views/notifications/index.js.erb
$('.notifications').find("ul")
	.append('<%= escape_javascript render(@notifications) %>');
$('.pagination-notifies')
	.replaceWith('<%= escape_javascript will_paginate(@notifications, class: "pagination-notifies") %>');