config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'	# named routes
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	get '/index', to: 'users#index'
	get '/notification/:id/link_through', to: 'notifications#link_through',
										 as: :link_through
	get '/notifications', to: 'notifications#index'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :comments,		only: [:create, :destroy]
	resources :likes, 			only: [:create, :destroy]
	resources :users
	resources :microposts,		only: [:create, :destroy, :show]
	resources :relationships,	only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token	# create accessible attribute remember_token
	before_save {self.email.downcase!}
	validates :name, presence: true, length: {maximum: 50}
	VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
					  format: {with: VALIDATE_EMAIL_REGEX},
					  uniqueness: {case_sensitive: false}
	has_secure_password
	mount_uploader :avatar, AvatarUploader
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true
	validate :avatar_size
	has_many :microposts, dependent: :destroy
	has_many :active_relationships, class_name: "Relationship",
									foreign_key: "follower_id",
									dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
									foreign_key: "followed_id",
									dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	has_many :likes , dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :notifications, dependent: :destroy

	# Returns the hash digest of the given string.
	def self.digest string
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	# Search users
	def self.search name
		User.where("name like ?", "%#{name}%")
	end

	def already_like?(micropost)
		micropost.likes.find_by(user_id: self.id) != nil
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated? remember_token
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end

	# Defines a proto-feed.
	# See "Following users" for the full implementation.
	def feed
		following_ids = "SELECT followed_id FROM relationships
						WHERE follower_id = :user_id"
		Micropost.where("user_id IN (#{following_ids}) 
						OR user_id = :user_id", user_id: id)
	end

	# Follows a user
	def follow other_user
		active_relationships.create(followed_id: other_user.id)
	end

	# Unfollow a user
	def unfollow other_user
		following.delete(other_user)
	end

	# Return true if the current user is following the other user
	def following? other_user
		following.include?(other_user)
	end

	private
		def avatar_size
			if avatar.size > 5.megabytes
				error.add(:avatar, "should be less than 5MB")
			end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update, :delete, :index]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def index
		if(params[:search])
			@users = User.search(params[:search]).order('name ASC')
				.paginate(page: params[:page], per_page: 6)
		else
			@users = User.all.order('name ASC')
				.paginate(page: params[:page], per_page: 6)
		end
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@user1 = @user

		if params[:last_id]
			@microposts = @user.microposts.where("id < ? and user_id = ?", 
				params[:last_id], @user.id)
			render json: @microposts.as_json
		else
			@microposts = @user.microposts
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :gender, :password,
										 :password_confirmation, :avatar)
		end

		# Before filters

		# Confirms the correct user
		def correct_user
			@user = User.find(params[:id])
			redirect_to root_url unless current_user?(@user)
		end

		# Confirms an admin user
		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_content_hided.html.erb
<div class="comments-list" style="display: none;">
	<%= render 'microposts/comments_list', micropost: micropost %>
</div>
<% if current_user == micropost.user %>
	<div class="setting" style="display: none;">
		<div class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				<b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
				<li><%= link_to "Delete", micropost, method: :delete %></li>
			</ul>
		</div>
	</div>
<% end %>
<div class="text-content" style="display: none;">
	<%= link_to micropost.user.name ,micropost.user %>
	<%= micropost.content %>
</div>
<div class="timestamp" style="display: none;">
	<%= time_ago_in_words(micropost.created_at) %>
</div>
<div class="number-like" style="display: none;">
	<%= micropost.likes.count %> 
	<%= "Like".pluralize(micropost.likes.count) %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
	<div><%= hidden_field_tag :followed_id, @user.id %></div>
	<%= f.submit "Follow", class: "btn follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<div class="follow-form-<%= @user.id %>">
	<% if current_user.following?(@user) %>
		<%= render 'users/unfollow' %>
	<% else %>
		<%= render 'users/follow' %>
	<% end %>
</div>

app/views/users/_popup_post.html.erb
<div class="modal fade" id="post-modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<div class="micropost-img">
					
				</div>
				<div class="micropost-info">
					<div class="base-info">
						<div class="base-left-block">
							<div class="text-content"></div>
							<div class="number-like"></div>
						</div>
						<div class="base-right-block">
							<div class="setting"></div>
							<div class="time-stamp"></div>
						</div>
					</div>
					<hr>
					<div class="comments-list"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
			 html: {method: :delete},
			 remote: true) do |f| %>
	<%= f.submit "Following", class: "btn unfollow-btn"%>
<% end %>

app/views/users/_user.html.erb
<% if user.admin? == false %>
	<div class="row">
		<div class="user">
			<div class="avatar">
				<% if user.avatar? %>
					<%= link_to image_tag(user.avatar.url(:thumb_small)), user %>
				<% else %>
					<% if user.gender == "Male" %>
						<%= link_to image_tag(user.avatar.default_url("ava-default-male.jpg")), user %>
					<% else %>
						<%= link_to image_tag(user.avatar.default_url("ava-default-female.png")), user %>
					<% end %>
				<% end %>
			</div>
			<div class="user-info">
				<div class="name"><%= link_to user.name, user %></div>
				<br>
				<div class="info-detail">
					<div class="number-post">
						<strong><%= user.microposts.count %></strong> 
						<%= "Post".pluralize(user.microposts.count) %>
					</div>
					<div class="number-follower number-follower-<%= user.id %>">
						<strong><%= user.followers.count %></strong> 
						<%= "Follower".pluralize(user.followers.count) %>
					</div>
					<div class="number-following number-following-<%= user.id %>">
						<strong><%= user.following.count %></strong> 
						<%= "Following".pluralize(user.following.count) %>
					</div>
				</div>
			</div>
			<div class="follow-form">
				<% if current_user != user %>
					<% @user = user %>
					<%= render "follow_form" if logged_in? %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="edit-profile">
	<div class="left-block-edit">
		<%= form_for(@user) do |f| %>
			<div class="propic-edit">
				<% if @user.avatar? %>
					<%= image_tag @user.avatar.url, id: "avatar" %>
				<% else %>
					<% if @user.gender == "Male" %>
						<%= image_tag @user.avatar.default_url("ava-default-male.jpg"), id: "avatar" %>
					<% else %>
						<%= image_tag @user.avatar.default_url("ava-default-female.png"), id: "avatar" %>
					<% end %>
				<% end %>
				<%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png",    id: "upload-pic" %>
				<a class="upload-new-pic" href="#">
					<i class="fa fa-camera" aria-hidden="true"></i>Update Avatar
				</a>
			</div>
			<div class="name-edit">
				<% if @user.errors[:name].length != 0%>
					<div class="error-messages"><%= @user.errors[:name][0] %></div>
				<% end %>
				<%= f.label :name, "Registered Name" %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="email-edit">
				<% if @user.errors[:email].length != 0%>
					<div class="error-messages"><%= @user.errors[:email][0] %></div>
				<% end %>
				<%= f.label :email, "Registered Email" %>
				<%= f.text_field :email, class: "form-control" %>
			</div>
			<div class="gender-edit">
				<%= f.radio_button :gender, "Male", checked: @user.gender == "Male", 
									id: "male-radio" %>
				<%= f.label :gender, "Male", for: "male-radio" %>
				<%= f.radio_button :gender, "Female", checked: @user.gender == "Female",
									id: "female-radio" %>
				<%= f.label :gender, "Female", for: "female-radio" %>
			</div>
			<br><br>
			<%= f.submit "Click Me To Update", class: "btn btn-success" %>
		<% end %>
	</div>
	<div class="right-block-edit">
		<div class="alert alert-info" role="alert">
			<h3>About Update Profile</h3>
			<div class="about-me-content">Nullam blandit gravida viverra. Etiam turpis erat, sagittis sit amet felis non, porta porta justo. Integer ornare nibh nulla, id pulvinar metus cursus semper. Vivamus dictum pellentesque mi. Vivamus ipsum tellus, mattis non ex sed, semper sodales ligula. Vivamus luctus lorem.</div>
		</div>
		<div class="btn-social-network-list">
			<a class="btn facebook-btn" href="#"><i class="fa fa-facebook" aria-hidden="true"></i>Facebook</a>
			<a class="btn google-btn" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i>Google+</a>
			<a class="btn twitter-btn" href="#"><i class="fa fa-twitter" aria-hidden="true"></i>Twitter</a>
			<a class="btn linkedin-btn" href="#"><i class="fa fa-linkedin" aria-hidden="true"></i>Linkedin</a>
		</div>
		<p style="margin-bottom: 38px;"></p>
		<h3>Change Your Password</h3>
		<%= form_for(@user) do |f| %>
			<% if @user.errors[:password].length != 0%>
				<div class="error-messages"><%= @user.errors[:password][0] %></div>
			<% end %>
			<%= f.label :password, "Enter New Password" %>
			<%= f.password_field :password, class: "form-control" %>
		
			<% if @user.errors[:password_confirmation].length != 0%>
				<div class="error-messages"><%= @user.errors[:password_confirmation][0] %></div>
			<% end %>
			<%= f.label :password_confirmation, "Confirm New Password" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>
			<p style="margin-bottom: 73px;"></p>
			<%= f.submit "Change Password", class: "btn btn-warning" %>
		<% end %>
	</div>
</div>
<script type="text/javascript">
	function readURL(input){
		if(input.files && input.files[0]){
			var reader = new FileReader();

			reader.onload = function(e){
				$("#avatar")
					.attr("src", e.target.result);
			};
			reader.readAsDataURL(input.files[0]);
		}
	}
	$("a.upload-new-pic").on("click",function(e){
		e.preventDefault();
		$("#upload-pic:hidden").trigger("click");
	});
	$("#upload-pic:hidden").change(function(){
		readURL(this);
	});
</script>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<div class="index-users">
	<div class="container">
		<div class="search-filter">
			<div class="title">Users search</div>
			<%= form_tag users_path, method: "get" do %>
				<%= text_field_tag :search, nil, {placeholder: "Luna Lovegood"} %>
				<%= check_box_tag :dear_friend %>
				<%= label_tag :dear_friend %>
				<br>
				<%= check_box_tag :hot_friend %>
				<%= label_tag :hot_friend, "Hot friends" %>
				<br>
				<%= check_box_tag :hard_working %>
				<%= label_tag :hard_working, "Hard working friends" %>
				<br>
				<%= submit_tag "Search", class: "btn btn-primary" %>
			<% end %>
		</div>
		<div class="list-users">
			<div class="container">
				<% @users.each do |user| %>
					<% unless user.admin? %>
						<% @user = user %>
						<%= render user %>
					<% end %>
				<% end %>
			</div>
			<%= will_paginate @users, class: "pagination-users" %>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function() {
		if ($('.pagination-users').length) {
			$(window).scroll(function() {
				var url = $('.pagination-users .next_page').find("a").attr('href');
				if (url && url != '#' && $(window).scrollTop() > $(document).height() - $(window).height() - 10) {
					$('.pagination-users').html(
						"<i class='fa fa-spinner fa-spin fa-3x fa-fw'></i>"
						+ "<span class='sr-only'>Loading...</span>");
					console.log(url);
					return $.getScript(url);
				}
			});
			return $(window).scroll();
		}
	});
</script>

app/views/users/index.js.erb
$('.list-users').find(".container")
	.append('<%= escape_javascript render(@users) %>');
$('.pagination-users').replaceWith(
	'<%= escape_javascript will_paginate(@users, class: "pagination-users") %>');

app/views/users/new.html.erb
<div id="login-box">
	<div class="left-block">
		<h1>Sign up</h1>
		<%= form_for(@user, url: signup_path) do |f| %>
			<% if @user.errors[:name].length != 0 %>
				<div class="error-messages"><%= @user.errors[:name][0] %></div>
			<% end %>
			<%= f.text_field :name, placeholder: "Harry Potter 90", class: "form-control" %>

			<% if @user.errors[:email].length != 0 %>
				<div class="error-messages"><%= @user.errors[:email][0] %></div>
			<% end %>
			<%= f.email_field :email, placeholder: "harry@gmail.com", class: "form-control" %>

			<% if @user.errors[:password].length != 0 %>
				<div class="error-messages"><%= @user.errors[:password][0] %></div>
			<% end %>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>

			<% if @user.errors[:password_confirmation].length != 0 %>
				<div class="error-messages"><%= @user.errors[:password_confirmation][0] %></div>
			<% end %>
			<%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %>

			<%= f.radio_button :gender, "Male", checked: true, id: "male-radio" %>
			<%= f.label :gender, "Male", for: "male-radio" %>
			<%= f.radio_button :gender, "Female", checked: false, id: "female-radio" %>
			<%= f.label :gender, "Female", for: "female-radio" %>
			<br>
			<%= f.submit "Enjoy With Us !" %>
		<% end %>
		<br>
		<p>Already had account? <%= link_to "Let's go", login_path %></p>
	</div>
	<div class="right-block">
		<span class="login-with">Sign in with<br>social network</span>
		<button class="social-signin facebook">Log in with facebook</button>
		<button class="social-signin google">Log in with Google+</button>
	</div>
	<div class="or">OR</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container user-profile">
	<br><br>
	<div class="row">
		<div class="col-xs-4">
			<div class="avatar">
				<% if @user.avatar? %>
					<%= image_tag @user.avatar.url(:thumb) %>
				<% else %>
					<% if @user.gender == "Male" %>
						<%= image_tag @user.avatar.default_url("ava-default-male.jpg") %>
					<% else %>
						<%= image_tag @user.avatar.default_url("ava-default-female.png") %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="col-xs-8">
			<div class="name-express">
				<div class="name"><%= @user.name %></div>
				<div class="config-area">
					<% if current_user?(@user) %>
						<%= link_to "Edit Profile", edit_user_path(current_user), id: "edit-profile-btn" %>
					<% else %>
						<% if @user.admin? == false %>
							<%= render 'follow_form' if logged_in? %>
						<% end %>
					<% end %>
				</div>
			</div>
			<div class="user-info-express">
				<div class="number number-post">
					<strong><%= @user.microposts.count %></strong> 
					<%= "Post".pluralize(@user.microposts.count) %>
				</div>
				<div class="number number-follower number-follower-<%= @user.id %>">
					<a href="#followers-modal" data-toggle="modal" data-target="#followers-modal">
						<strong><%= @user.followers.count %></strong> 
						<%= "Follower".pluralize(@user.followers.count) %>
					</a>
				</div>
				<div class="number number-following number-following-<%= @user.id %>">
					<a href="#following-modal" data-toggle="modal" data-target="#following-modal">
						<strong><%= @user.following.count %></strong> 
						<%= "Following".pluralize(@user.following.count) %>
					</a>
				</div>
			</div>
		</div>
	</div>
	<br><br>
	<% if @microposts.any? %>
		<% @microposts.each_with_index do |micropost, index| %>
			<% if index % 3 == 0 %>
				<div class="row pic-row">
					<% range = Range.new(index, index + 2) %>
					<% @microposts.each_with_index do |micropost, index1| %>
						<% if range.cover?(index1) %>
							<div class="col-xs-4 picture" data-id="<%= micropost.id %>" data-toggle="modal" data-target="#post-modal">
								<%= image_tag micropost.picture.url %>
								<%= render 'users/content_hided', micropost: micropost %>
								<div class="img-info">
									<div class="number-like">
										<%= fa_icon "heart" %>
										<%= micropost.likes.count %>
									</div>
									<div class="number-comment"><%= fa_icon "comment" %> <%= micropost.comments.count %></div>
								</div>
							</div>
						<% end %>	
					<% end %>
				</div>
			<% end %>
		<% end %>
	<% else %>
		<div class="row">
			<div class="default-content">
				<img src="/assets/img-default.jpg">
				<div class="quote">
					Start capturing and sharing your moments.
					<br>Connecting people.
					<div class="branding-name">Anigram</div>
				</div>
			</div>
		</div>
	<% end %>
	<br>
	<!--<div class="row">
		<div class="col-xs-3 col-xs-push-5">
			<% if @microposts.any? %>
				<button class="btn-load-more">Load more</button>
			<% end %>
		</div>
	</div>-->
</div>
<%= render 'users/popup_post' %>

<% @user = @user1 %>
<%= render 'shared/show_following', user: @user %>
<% @user =  @user1 %>
<%= render 'shared/show_followers', user: @user %>
<% @user = @user1 %>

<script type="text/javascript">
	$(".picture").click(function(){
		var image = $(this).children("img").clone();
		var textContent = $(this).children(".text-content").html();
		var numberLike = $(this).children(".number-like").text();
		var timeStamp = $(this).children(".timestamp").text();
		var commentsList = $(this).children(".comments-list").html();
		var setting = $(this).children(".setting").html();

		$("#post-modal").find(".micropost-img").html(image);
		$("#post-modal").find(".text-content").html(textContent);
		$("#post-modal").find(".number-like").text(numberLike);
		$("#post-modal").find(".comments-list").html(commentsList);
		$("#post-modal").find(".time-stamp").text(timeStamp);
		$("#post-modal").find(".base-info").find(".setting").html(setting);
	});
	
	$(function(){
		if(<%= @user.microposts.count %> <= 3){
			$(".btn-load-more").hide();
		}
		$(".btn-load-more").click(function(){
			$(this).hide();
			var last_post_id = $(".picture").last().attr("data-id");
			$.ajax({
				type: "GET",
				url: "<%= @user.id %>",
				data: {
					last_id: last_post_id
				},
				dataType: "json",
				success: function(data){
					if(data.length > 0){
						$(".btn-load-more").show();
						data.forEach(function(item, index){
							if(index % 3 == 0){
								$(".pic-row").last().after("<div class='row pic-row'></div>");
							}
							$(".pic-row").last().append(
								"<div class='col-xs-4 picture' data-id='" + item.id + "'>"
								+ "	<img src='" + item.picture.url + "'>"
								+ "	<div class='img-info'>"
								+ "	<div class='number-like'><i class='fa fa-heart'></i> 221</div>"
								+ "	<div class='number-comment'><i class='fa fa-comment'></i> 376</div>"
								+ " </div>"
								+ "</div>");
						});
						var last_post_id = $(".picture").last().attr("data-id");
						$.ajax({
							type: "GET",
							url: "<%= @user.id %>",
							data: {
								last_id: last_post_id
							},
							dataType: "json",
							success: function(data){
								if(data.length == 0){
									$(".btn-load-more").hide();
								}
							}
						});
					}
				}
			});
		});
	});
</script>