config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'	# named routes
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	get '/index', to: 'users#index'
	get '/notification/:id/link_through', to: 'notifications#link_through',
										 as: :link_through
	get '/notifications', to: 'notifications#index'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :comments,		only: [:create, :destroy]
	resources :likes, 			only: [:create, :destroy]
	resources :users
	resources :microposts,		only: [:create, :destroy, :show]
	resources :relationships,	only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	mount_uploader :picture, PictureUploader
	validates :user_id, presence: true
	validates :content, length: {maximum: 155}
	validates :picture, presence: true
	validate :picture_size
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :notifications, dependent: :destroy
	acts_as_taggable 	# Alias for acts_as_taggable_on :tags
	ActsAsTaggableOn.delimiter = ' '

	private

		# Validates the size of an uploaded image
		def picture_size
			if picture.size > 1.megabytes
				errors.add(:picture, "should be less than 1MB")
			end
		end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user,   only: :destroy

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			redirect_to root_url
		else
			@feed_items = []
			flash[:danger] = @micropost.errors.full_messages.join(" & ")
			redirect_to root_url
		end
	end

	def show
		@micropost = Micropost.find_by(id: params[:id])
	end

	def destroy
		@notifications = Notification.where(micropost_id: @micropost.id)
		if @notifications != nil
			@notifications.each do |notification|
				notification.destroy
			end
		end
		@micropost.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private

		def micropost_params
			params.require(:micropost).permit(:content, :picture, :tag_list)
		end

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
			redirect_to root_url if @micropost.nil?
		end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_avatar_display.html.erb
<% if micropost.user.avatar? %>
	<%= link_to image_tag(micropost.user.avatar.url), micropost.user %>
<% else %>
	<% if micropost.user.gender == "Male" %>
		<%= link_to image_tag(micropost.user.avatar.default_url("ava-default-male.jpg")), micropost.user %>
	<% else %>
		<%= link_to image_tag(micropost.user.avatar.default_url("ava-default-female.png")), micropost.user %>
	<% end %>
<% end %>

app/views/microposts/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
	<% @user = User.find_by(id: comment.user_id) %>
	<div class="user-name">
		<%= link_to @user.name, @user %>
	</div>
	<div class="comment-content"><%= comment.content %></div>
	<% if current_user == @user || current_user == micropost.user %>
		<div class="setting">
			<div class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<b class="glyphicon glyphicon-remove"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Delete comment", comment_path(id: comment.id), method: :delete, remote: true %></li>
				</ul>
			</div>
		</div>
	<% end %>
	<div class="reply">
		<div class="reply-link">Reply</div> &#8226; 
		<div class="comment-time">
			<%= comment.created_at.strftime("%B #{comment.created_at.day}, %Y at %H:%M") %>
		</div>
	</div>
</div>

app/views/microposts/_comment_form.html.erb
<%= form_tag comments_path(micropost_id: micropost.id), remote: true do %>
	<%= text_field_tag :content, nil, placeholder: "Add a comment..." %>
<% end %>

app/views/microposts/_comment_hided.html.erb
<div class="comment" id="comment-<%= comment.id %>" style="display: none;">
	<% @user = User.find_by(id: comment.user_id) %>
	<div class="user-name">
		<%= link_to @user.name, @user %>
	</div>
	<div class="comment-content"><%= comment.content %></div>
	<% if current_user == @user || current_user == micropost.user %>
		<div class="setting">
			<div class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<b class="glyphicon glyphicon-remove"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Delete comment", comment_path(id: comment.id), method: :delete, remote: true %></li>
				</ul>
			</div>
		</div>
	<% end %>
</div>

app/views/microposts/_comments_list.html.erb
<% @comments = micropost.comments %>
<% @numberComments = @comments.length %>
<% if @numberComments > 4 %>
	<div class="toggle-comments-list">view all <%= @numberComments %> comments</div>
	<% @comments.each_with_index do |comment, index| %>
		<% if index < @numberComments - 4 %>
			<%= render 'microposts/comment_hided', comment: comment, micropost: micropost %>
		<% else %>
			<%= render 'microposts/comment', comment: comment, micropost: micropost %>
		<% end %>
	<% end %>
<% else %>
	<% @comments.each do |comment| %>
		<%= render 'microposts/comment', comment: comment, micropost: micropost %>
	<% end %>
<% end %>

<script type="text/javascript">
	$(document).on("click", "div.toggle-comments-list", function(){
		$(this).parent().find(".comment").fadeIn();
		$(this).fadeOut();
	});
</script>

app/views/microposts/_like_form.html.erb
<% if current_user.already_like?(micropost) %>
	<% @like = Like.where("user_id = ? and micropost_id = ?", current_user.id, micropost.id).first %>
	<div id="micropost-like-<%= micropost.id %>">
		<%= link_to like_path(id: @like.id), method: :delete, remote: true do %>
			<%= fa_icon "heart" %>
		<% end %>
	</div>
<% else %>
	<div id="micropost-like-<%= micropost.id %>">
		<%= link_to likes_path(micropost_id: micropost.id), method: :post, remote: true do %>
			<%= fa_icon "heart-o" %>
		<% end %>
	</div>
<% end %>

app/views/microposts/_micropost.html.erb
<li class="micropost" id="micropost-<%= micropost.id %>">
	<%= render 'microposts/micropost_content', micropost: micropost %>
</li>

app/views/microposts/_micropost_content.html.erb
<div class="head">
	<div class="avatar">
		<%= render 'microposts/avatar_display', micropost: micropost %>
	</div>
	<div class="user-name">
		<%= link_to micropost.user.name, micropost.user %>			
	</div>
	<div class="timestamp">
		<%= time_ago_in_words(micropost.created_at) %>
	</div>
	<%= render 'shared/setting_post', micropost: micropost %>
</div>
<div class="content">
	<div class="image-content">
		<%= image_tag micropost.picture.url if micropost.picture? %>
	</div>
	<div class="number-like" id="number-like-<%= micropost.id %>"><%= micropost.likes.count %> <%= "like".pluralize(micropost.likes.count) %></div>
	<div class="micropost-content">
		<% if micropost.content.length != 0%>
			<%= link_to micropost.user.name, micropost.user %> 
			<div class="text-content">
				<%= micropost.content %>
			</div>
		<% end %>
		<div class="tag-lists">
			<% micropost.tag_list.each do |tag| %>
				<div class="tag"><%= tag %></div>
			<% end %>
		</div>
	</div>
</div>
<div class="comment-section">
	<div class="comments-list">
		<%= render 'microposts/comments_list', micropost: micropost %>
	</div>
	<div class="comment-form">
		<%= render 'microposts/like_form', micropost: micropost %>
		<%= render 'microposts/comment_form', micropost: micropost %>
	</div>
</div>

app/views/microposts/show.html.erb
<div class="show-micropost">
	<div class="micropost" id="micropost-<%= @micropost.id %>">
		<%= render 'microposts/micropost_content', micropost: @micropost %>
	</div>
</div>