config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'	# named routes
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	get '/index', to: 'users#index'
	get '/notification/:id/link_through', to: 'notifications#link_through',
										 as: :link_through
	get '/notifications', to: 'notifications#index'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :comments,		only: [:create, :destroy]
	resources :likes, 			only: [:create, :destroy]
	resources :users
	resources :microposts,		only: [:create, :destroy, :show]
	resources :relationships,	only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<nav>
	<div class="nav-wrapper">
		<a href="/" class="brand-logo"><%= fa_icon "instagram" %> | AniGram</a>
		<% if logged_in? %>
			<%= form_tag users_path, method: "get", class: "users-search" do %>
				<%= text_field_tag :search, params[:search], class: "search-box", placeholder: "Search..." %>
			<% end %>
		<% end %>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
			<% if logged_in? %>
				<li class="dropdown">
					<a href="#" charset="dropdown-toggle" data-toggle="dropdown">
						<% count = 0 %>
						<% current_user.notifications.each do |notification| %>
							<% if !notification.read %>
								<% count += 1 %>
							<% end %>
						<% end %>
						<% if count == 0 %>
							<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
						<% else %>
							<span class="glyphicon glyphicon-heart" style="color: #fa3e3e;" aria-hidden="true"></span>
						<% end %>
					</a>
					<ul class="dropdown-menu notifi-dropdown">
						<li>Notifications</li>
						<%= render current_user.notifications.order('id DESC').first(3) %>
						<li>
							<%= link_to "View All", notifications_path %>
						</li>
					</ul>
				</li>
				<li>
					<%= link_to current_user do %>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					<% end %>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Settings", edit_user_path(current_user) %></li>
						<li><%= link_to "Log out", logout_path, method: "delete" %></li>
					</ul>
				</li>
			<% else %>
				<% if current_page?(root_path) %>
					<li><a href="#about-path" onclick="internal_link_click(this)">About</a></li>
					<li><a href="#portfolio-path" onclick="internal_link_click(this)">Portfolio</a></li>
					<li><a href="/login">Sign In</a></li>
				<% end %>
			<% end %>
		</ul>
	</div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<link rel="icon" type="image/png" href="/assets/icon.png">
		<%= render "layouts/rails_default" %>
		<%= render "layouts/shim" %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
	</body>
</html>